# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 269)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pb_sync = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_sync.sizePolicy().hasHeightForWidth())
        self.pb_sync.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pb_sync.setFont(font)
        self.pb_sync.setObjectName("pb_sync")
        self.gridLayout_4.addWidget(self.pb_sync, 6, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l_progress = QtWidgets.QLabel(self.centralwidget)
        self.l_progress.setObjectName("l_progress")
        self.gridLayout_3.addWidget(self.l_progress, 0, 0, 1, 1)
        self.pb_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.pb_progress.setProperty("value", 0)
        self.pb_progress.setObjectName("pb_progress")
        self.gridLayout_3.addWidget(self.pb_progress, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.le_bucket = QtWidgets.QLineEdit(self.centralwidget)
        self.le_bucket.setObjectName("le_bucket")
        self.gridLayout.addWidget(self.le_bucket, 0, 1, 1, 1)
        self.l_bucket = QtWidgets.QLabel(self.centralwidget)
        self.l_bucket.setObjectName("l_bucket")
        self.gridLayout.addWidget(self.l_bucket, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_sync_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sync_dir.setObjectName("le_sync_dir")
        self.gridLayout_2.addWidget(self.le_sync_dir, 0, 1, 1, 1)
        self.l_sync_dir = QtWidgets.QLabel(self.centralwidget)
        self.l_sync_dir.setObjectName("l_sync_dir")
        self.gridLayout_2.addWidget(self.l_sync_dir, 0, 0, 1, 1)
        self.tb_browser = QtWidgets.QToolButton(self.centralwidget)
        self.tb_browser.setObjectName("tb_browser")
        self.gridLayout_2.addWidget(self.tb_browser, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 2, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.le_access_key = QtWidgets.QLineEdit(self.centralwidget)
        self.le_access_key.setObjectName("le_access_key")
        self.gridLayout_6.addWidget(self.le_access_key, 0, 1, 1, 1)
        self.l_access_key = QtWidgets.QLabel(self.centralwidget)
        self.l_access_key.setObjectName("l_access_key")
        self.gridLayout_6.addWidget(self.l_access_key, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 3, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.le_secret_key = QtWidgets.QLineEdit(self.centralwidget)
        self.le_secret_key.setObjectName("le_secret_key")
        self.gridLayout_7.addWidget(self.le_secret_key, 0, 1, 1, 1)
        self.l_secret_key = QtWidgets.QLabel(self.centralwidget)
        self.l_secret_key.setObjectName("l_secret_key")
        self.gridLayout_7.addWidget(self.l_secret_key, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 455, 22))
        self.menuBar.setObjectName("menuBar")
        self.m_languages = QtWidgets.QMenu(self.menuBar)
        self.m_languages.setObjectName("m_languages")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.m_languages.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QiniuSyncer"))
        self.pb_sync.setText(_translate("MainWindow", "pb_sync"))
        self.l_progress.setText(_translate("MainWindow", "Progress"))
        self.l_bucket.setText(_translate("MainWindow", "l_bucket"))
        self.l_sync_dir.setText(_translate("MainWindow", "l_sync_dir"))
        self.tb_browser.setText(_translate("MainWindow", "..."))
        self.l_access_key.setText(_translate("MainWindow", "l_access_key"))
        self.l_secret_key.setText(_translate("MainWindow", "l_secret_key"))
        self.m_languages.setTitle(_translate("MainWindow", "Languages"))
